-- Retired.
-- The old wholesaling scripts in this file promised a 7-14 day close,
-- "we cover all closing costs," and "no fees."
-- Do not run those statements.
--
-- Current answers live in lib/knowledge.js.
-- Apply them to the live database with:
--   node scripts/update-kb-facts.js /app/data/sms-agent.db
-- The server also applies them when it starts.
