-- Retired.
-- This file used to delete the knowledge base and load wholesaling scripts
-- that promised a 7-14 day close, "we cover all closing costs," and "no fees."
-- Do not run those old statements.
--
-- The current answers live in lib/knowledge.js.
-- Apply them to an existing sms-agent.db with:
--   node scripts/update-kb-facts.js
-- The server also applies them when it starts.
